import {MigrationInterface, QueryRunner} from "typeorm";

export class ChangePrimaryGeneratedColumn1594301843889 implements MigrationInterface {
    name = 'ChangePrimaryGeneratedColumn1594301843889'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "label_users_user" ("labelInCommonId" integer NOT NULL, "userInCommonId" integer NOT NULL, CONSTRAINT "PK_823ea054775f328a808b131e9c6" PRIMARY KEY ("labelInCommonId", "userInCommonId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_088f637a172dab5f8a9508646d" ON "label_users_user" ("labelInCommonId") `);
        await queryRunner.query(`CREATE INDEX "IDX_94a293541ce58e345277821f67" ON "label_users_user" ("userInCommonId") `);
        await queryRunner.query(`CREATE TABLE "label_records_record" ("labelInCommonId" integer NOT NULL, "recordInCommonId" integer NOT NULL, CONSTRAINT "PK_e0e83ee0ce8170d83fd2dd9ac93" PRIMARY KEY ("labelInCommonId", "recordInCommonId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_b4d2c533e79535b79ecf15e5d6" ON "label_records_record" ("labelInCommonId") `);
        await queryRunner.query(`CREATE INDEX "IDX_1b853c485545482e80adef1cd0" ON "label_records_record" ("recordInCommonId") `);
        await queryRunner.query(`CREATE TABLE "label_musics_music" ("labelInCommonId" integer NOT NULL, "musicInCommonId" integer NOT NULL, CONSTRAINT "PK_0d47c8e0a365ab2ab07f6e3c4e7" PRIMARY KEY ("labelInCommonId", "musicInCommonId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_b3d4ecb49b1652d20316f0463c" ON "label_musics_music" ("labelInCommonId") `);
        await queryRunner.query(`CREATE INDEX "IDX_4e029615a53cea0d2a4c43c868" ON "label_musics_music" ("musicInCommonId") `);
        await queryRunner.query(`CREATE TABLE "label_bands_band" ("labelInCommonId" integer NOT NULL, "bandInCommonId" integer NOT NULL, CONSTRAINT "PK_260b8dbc39cf972739188c736d7" PRIMARY KEY ("labelInCommonId", "bandInCommonId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_da5243cecb29840e6aaa043bf9" ON "label_bands_band" ("labelInCommonId") `);
        await queryRunner.query(`CREATE INDEX "IDX_5a0a392c6e3c47242e0663cd0f" ON "label_bands_band" ("bandInCommonId") `);
        await queryRunner.query(`CREATE TABLE "label_artists_artist" ("labelInCommonId" integer NOT NULL, "artistInCommonId" integer NOT NULL, CONSTRAINT "PK_29653196a8d187408d5bcd074ef" PRIMARY KEY ("labelInCommonId", "artistInCommonId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_f305bb394076e0908217d1ca5a" ON "label_artists_artist" ("labelInCommonId") `);
        await queryRunner.query(`CREATE INDEX "IDX_65992b1a5580f3ff4e4a566940" ON "label_artists_artist" ("artistInCommonId") `);
        await queryRunner.query(`CREATE TABLE "music_users_user" ("musicInCommonId" integer NOT NULL, "userInCommonId" integer NOT NULL, CONSTRAINT "PK_5f851be1d32beac6eb84c03dcc6" PRIMARY KEY ("musicInCommonId", "userInCommonId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_00b4e628cc01e82fe007f6f763" ON "music_users_user" ("musicInCommonId") `);
        await queryRunner.query(`CREATE INDEX "IDX_57ed247d1ff420dc8c13645bbc" ON "music_users_user" ("userInCommonId") `);
        await queryRunner.query(`CREATE TABLE "music_records_record" ("musicInCommonId" integer NOT NULL, "recordInCommonId" integer NOT NULL, CONSTRAINT "PK_86733a29113b61a44ac3f0e4e01" PRIMARY KEY ("musicInCommonId", "recordInCommonId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_4a7735e89ad4f3b65b2510cef6" ON "music_records_record" ("musicInCommonId") `);
        await queryRunner.query(`CREATE INDEX "IDX_6a92b165ab4cb0b912eeefc870" ON "music_records_record" ("recordInCommonId") `);
        await queryRunner.query(`CREATE TABLE "music_labels_label" ("musicInCommonId" integer NOT NULL, "labelInCommonId" integer NOT NULL, CONSTRAINT "PK_59c57e7fd080eb6b2c3705fca03" PRIMARY KEY ("musicInCommonId", "labelInCommonId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_c4f803b5c7b3afe82483d6874c" ON "music_labels_label" ("musicInCommonId") `);
        await queryRunner.query(`CREATE INDEX "IDX_942627b8813020cc805cb36617" ON "music_labels_label" ("labelInCommonId") `);
        await queryRunner.query(`CREATE TABLE "music_bands_band" ("musicInCommonId" integer NOT NULL, "bandInCommonId" integer NOT NULL, CONSTRAINT "PK_95739ba5be9d8c016e6800a7032" PRIMARY KEY ("musicInCommonId", "bandInCommonId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_3ed21a53a1796c72c657f10252" ON "music_bands_band" ("musicInCommonId") `);
        await queryRunner.query(`CREATE INDEX "IDX_7cca8c88113973af66867c1680" ON "music_bands_band" ("bandInCommonId") `);
        await queryRunner.query(`CREATE TABLE "music_artists_artist" ("musicInCommonId" integer NOT NULL, "artistInCommonId" integer NOT NULL, CONSTRAINT "PK_dfc1dc66fc2ab79a0c1e0fa2ec2" PRIMARY KEY ("musicInCommonId", "artistInCommonId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_8a282f602f8c5b8cd1426f72b1" ON "music_artists_artist" ("musicInCommonId") `);
        await queryRunner.query(`CREATE INDEX "IDX_1deee4cef6329447199d1a82b0" ON "music_artists_artist" ("artistInCommonId") `);
        await queryRunner.query(`CREATE TABLE "record_users_user" ("recordInCommonId" integer NOT NULL, "userInCommonId" integer NOT NULL, CONSTRAINT "PK_975530bbaf9bf5745b0ced0de82" PRIMARY KEY ("recordInCommonId", "userInCommonId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_8c54e6e11d4b720d3df0271774" ON "record_users_user" ("recordInCommonId") `);
        await queryRunner.query(`CREATE INDEX "IDX_532851282aa95c4b401d3d9b57" ON "record_users_user" ("userInCommonId") `);
        await queryRunner.query(`CREATE TABLE "record_artists_artist" ("recordInCommonId" integer NOT NULL, "artistInCommonId" integer NOT NULL, CONSTRAINT "PK_734ddf3f82e8e90e00cb3756a77" PRIMARY KEY ("recordInCommonId", "artistInCommonId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_122ec5f408072ac39b5828351e" ON "record_artists_artist" ("recordInCommonId") `);
        await queryRunner.query(`CREATE INDEX "IDX_72497cff25641b2c6fd707cd5b" ON "record_artists_artist" ("artistInCommonId") `);
        await queryRunner.query(`CREATE TABLE "record_musics_music" ("recordInCommonId" integer NOT NULL, "musicInCommonId" integer NOT NULL, CONSTRAINT "PK_637ad24bc670d4120d07255edce" PRIMARY KEY ("recordInCommonId", "musicInCommonId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_9d3793a9465edcdc4135e9e920" ON "record_musics_music" ("recordInCommonId") `);
        await queryRunner.query(`CREATE INDEX "IDX_d9ebcd967ce415f2333dcf61be" ON "record_musics_music" ("musicInCommonId") `);
        await queryRunner.query(`CREATE TABLE "record_labels_label" ("recordInCommonId" integer NOT NULL, "labelInCommonId" integer NOT NULL, CONSTRAINT "PK_071af0f90001a77a99ec68e50eb" PRIMARY KEY ("recordInCommonId", "labelInCommonId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_6da6ad4991a07cdf1c92ae448d" ON "record_labels_label" ("recordInCommonId") `);
        await queryRunner.query(`CREATE INDEX "IDX_fe339ee5850d83bc3c3954b947" ON "record_labels_label" ("labelInCommonId") `);
        await queryRunner.query(`CREATE TABLE "record_bands_band" ("recordInCommonId" integer NOT NULL, "bandInCommonId" integer NOT NULL, CONSTRAINT "PK_0644dbaef45b86dc154f5a03bce" PRIMARY KEY ("recordInCommonId", "bandInCommonId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_0cc0e20eae5bc8ca2a87853806" ON "record_bands_band" ("recordInCommonId") `);
        await queryRunner.query(`CREATE INDEX "IDX_b3924c38c2c4a34483d5ad034d" ON "record_bands_band" ("bandInCommonId") `);
        await queryRunner.query(`CREATE TABLE "band_users_user" ("bandInCommonId" integer NOT NULL, "userInCommonId" integer NOT NULL, CONSTRAINT "PK_9ecb1b0a78ba18f69da75086dec" PRIMARY KEY ("bandInCommonId", "userInCommonId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_74662db770bb8884b284a43a6a" ON "band_users_user" ("bandInCommonId") `);
        await queryRunner.query(`CREATE INDEX "IDX_b0f9235ad70191593bd96ebb90" ON "band_users_user" ("userInCommonId") `);
        await queryRunner.query(`CREATE TABLE "band_records_record" ("bandInCommonId" integer NOT NULL, "recordInCommonId" integer NOT NULL, CONSTRAINT "PK_55e1ef931c844ac06f4bb3a7afd" PRIMARY KEY ("bandInCommonId", "recordInCommonId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_b584fd834262789d0f3086d2f6" ON "band_records_record" ("bandInCommonId") `);
        await queryRunner.query(`CREATE INDEX "IDX_38096136ba3b4119bb31ad2c44" ON "band_records_record" ("recordInCommonId") `);
        await queryRunner.query(`CREATE TABLE "band_musics_music" ("bandInCommonId" integer NOT NULL, "musicInCommonId" integer NOT NULL, CONSTRAINT "PK_92f1e98526c12284a7a78313f93" PRIMARY KEY ("bandInCommonId", "musicInCommonId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_067e03d51d85b0e2f6473dc5c4" ON "band_musics_music" ("bandInCommonId") `);
        await queryRunner.query(`CREATE INDEX "IDX_24e73c43d1a4d89bc1f5a0662e" ON "band_musics_music" ("musicInCommonId") `);
        await queryRunner.query(`CREATE TABLE "band_bands_label" ("bandInCommonId" integer NOT NULL, "labelInCommonId" integer NOT NULL, CONSTRAINT "PK_338bb08d5f509d8d8f81710be57" PRIMARY KEY ("bandInCommonId", "labelInCommonId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_6affa0410a03ad9a8a68aff024" ON "band_bands_label" ("bandInCommonId") `);
        await queryRunner.query(`CREATE INDEX "IDX_96b32d5c5c943b8af454418265" ON "band_bands_label" ("labelInCommonId") `);
        await queryRunner.query(`CREATE TABLE "band_artists_artist" ("bandInCommonId" integer NOT NULL, "artistInCommonId" integer NOT NULL, CONSTRAINT "PK_9ec934efecce06fa79e9ec42b43" PRIMARY KEY ("bandInCommonId", "artistInCommonId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_e7855b11ccff98db0995816425" ON "band_artists_artist" ("bandInCommonId") `);
        await queryRunner.query(`CREATE INDEX "IDX_6c8f852fff64cf4078a812fc0f" ON "band_artists_artist" ("artistInCommonId") `);
        await queryRunner.query(`CREATE TABLE "user_artists_artist" ("userInCommonId" integer NOT NULL, "artistInCommonId" integer NOT NULL, CONSTRAINT "PK_44248d04f0809e1bd10a7ef29b2" PRIMARY KEY ("userInCommonId", "artistInCommonId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_864f718bb7d05a873f70ff3940" ON "user_artists_artist" ("userInCommonId") `);
        await queryRunner.query(`CREATE INDEX "IDX_3e2b4550bdfc4dd7f57bfd6104" ON "user_artists_artist" ("artistInCommonId") `);
        await queryRunner.query(`CREATE TABLE "user_bands_band" ("userInCommonId" integer NOT NULL, "bandInCommonId" integer NOT NULL, CONSTRAINT "PK_b52375384ce53f59ea91b95bace" PRIMARY KEY ("userInCommonId", "bandInCommonId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_9a058a99805c83eb6d67620dfd" ON "user_bands_band" ("userInCommonId") `);
        await queryRunner.query(`CREATE INDEX "IDX_fa54807f630585e4de1ee8f7eb" ON "user_bands_band" ("bandInCommonId") `);
        await queryRunner.query(`CREATE TABLE "user_musics_music" ("userInCommonId" integer NOT NULL, "musicInCommonId" integer NOT NULL, CONSTRAINT "PK_cf02415e4e4b09316d9df96b912" PRIMARY KEY ("userInCommonId", "musicInCommonId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_e130dc5275cbd1600ac57e515c" ON "user_musics_music" ("userInCommonId") `);
        await queryRunner.query(`CREATE INDEX "IDX_acd8384b766cc1c0672d7a9976" ON "user_musics_music" ("musicInCommonId") `);
        await queryRunner.query(`CREATE TABLE "user_records_record" ("userInCommonId" integer NOT NULL, "recordInCommonId" integer NOT NULL, CONSTRAINT "PK_d8cca0fc268e9d9b41effb79bf2" PRIMARY KEY ("userInCommonId", "recordInCommonId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_dd2b6eee7e6ceea7833acb2ce3" ON "user_records_record" ("userInCommonId") `);
        await queryRunner.query(`CREATE INDEX "IDX_84d0c447b1d35e74d39aa9e7a7" ON "user_records_record" ("recordInCommonId") `);
        await queryRunner.query(`CREATE TABLE "user_labels_label" ("userInCommonId" integer NOT NULL, "labelInCommonId" integer NOT NULL, CONSTRAINT "PK_a845536924554fbf5e4e6892936" PRIMARY KEY ("userInCommonId", "labelInCommonId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_89b59b0e5441a78e66f82e4dde" ON "user_labels_label" ("userInCommonId") `);
        await queryRunner.query(`CREATE INDEX "IDX_d1ea408c2c23987b11dc7ff0a2" ON "user_labels_label" ("labelInCommonId") `);
        await queryRunner.query(`CREATE TABLE "artist_users_user" ("artistInCommonId" integer NOT NULL, "userInCommonId" integer NOT NULL, CONSTRAINT "PK_efa0a89e539f5cdd5e27abe80d0" PRIMARY KEY ("artistInCommonId", "userInCommonId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_f95f99d3ebce89d8cdd8bcd431" ON "artist_users_user" ("artistInCommonId") `);
        await queryRunner.query(`CREATE INDEX "IDX_4215f397941e0efe5ac7f6fcad" ON "artist_users_user" ("userInCommonId") `);
        await queryRunner.query(`CREATE TABLE "artist_records_record" ("artistInCommonId" integer NOT NULL, "recordInCommonId" integer NOT NULL, CONSTRAINT "PK_a67da54be204219ac7a018df71c" PRIMARY KEY ("artistInCommonId", "recordInCommonId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_90fdf85120e88a46acf16f2996" ON "artist_records_record" ("artistInCommonId") `);
        await queryRunner.query(`CREATE INDEX "IDX_6f417ea9c08b6657f620225fee" ON "artist_records_record" ("recordInCommonId") `);
        await queryRunner.query(`CREATE TABLE "artist_musics_music" ("artistInCommonId" integer NOT NULL, "musicInCommonId" integer NOT NULL, CONSTRAINT "PK_1b3e3b487718d07a516a9d243f2" PRIMARY KEY ("artistInCommonId", "musicInCommonId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_6fb690fb895d691ab918734f61" ON "artist_musics_music" ("artistInCommonId") `);
        await queryRunner.query(`CREATE INDEX "IDX_aaf98810dcea4847b5373c3c7d" ON "artist_musics_music" ("musicInCommonId") `);
        await queryRunner.query(`CREATE TABLE "artist_labels_label" ("artistInCommonId" integer NOT NULL, "labelInCommonId" integer NOT NULL, CONSTRAINT "PK_f45d71893a577d324ae44478ced" PRIMARY KEY ("artistInCommonId", "labelInCommonId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_991f42e0b968c18bf9029c2c05" ON "artist_labels_label" ("artistInCommonId") `);
        await queryRunner.query(`CREATE INDEX "IDX_7cb57bba282f5a53395d2f0c6c" ON "artist_labels_label" ("labelInCommonId") `);
        await queryRunner.query(`CREATE TABLE "artist_bands_band" ("artistInCommonId" integer NOT NULL, "bandInCommonId" integer NOT NULL, CONSTRAINT "PK_9cf32d09c0dcc6472cf52a6ae9f" PRIMARY KEY ("artistInCommonId", "bandInCommonId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_8f1a6760399cece036e086bd79" ON "artist_bands_band" ("artistInCommonId") `);
        await queryRunner.query(`CREATE INDEX "IDX_74d67fa805e303e2508c420a39" ON "artist_bands_band" ("bandInCommonId") `);
        await queryRunner.query(`ALTER TABLE "artist" DROP COLUMN "inCommonUpdatedat"`);
        await queryRunner.query(`ALTER TABLE "artist" DROP COLUMN "inCommonCreatedat"`);
        await queryRunner.query(`ALTER TABLE "artist" DROP CONSTRAINT "PK_10c1796675df147b3769c9bd32c"`);
        await queryRunner.query(`ALTER TABLE "artist" ADD CONSTRAINT "PK_55b76e71568b5db4d01d3e394ed" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "artist" DROP COLUMN "inCommonId"`);
        await queryRunner.query(`ALTER TABLE "artist" DROP COLUMN "followers"`);
        await queryRunner.query(`ALTER TABLE "artist" DROP COLUMN "likes"`);
        await queryRunner.query(`ALTER TABLE "artist" DROP COLUMN "passing"`);
        await queryRunner.query(`ALTER TABLE "artist" DROP COLUMN "birthday"`);
        await queryRunner.query(`ALTER TABLE "artist" DROP COLUMN "name"`);
        await queryRunner.query(`ALTER TABLE "artist" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "artist" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "artist" DROP CONSTRAINT "PK_55b76e71568b5db4d01d3e394ed"`);
        await queryRunner.query(`ALTER TABLE "artist" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "artist" ADD "id" SERIAL NOT NULL`);
        await queryRunner.query(`ALTER TABLE "artist" ADD CONSTRAINT "PK_55b76e71568b5db4d01d3e394ed" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "artist" ADD "createdAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "artist" ADD "updatedAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "artist" ADD "name" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "artist" ADD "birthday" TIMESTAMP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "artist" ADD "passing" TIMESTAMP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "artist" ADD "likes" integer NOT NULL`);
        await queryRunner.query(`ALTER TABLE "artist" ADD "followers" integer NOT NULL`);
        await queryRunner.query(`ALTER TABLE "artist" ADD "inCommonId" SERIAL NOT NULL`);
        await queryRunner.query(`ALTER TABLE "artist" DROP CONSTRAINT "PK_55b76e71568b5db4d01d3e394ed"`);
        await queryRunner.query(`ALTER TABLE "artist" ADD CONSTRAINT "PK_10c1796675df147b3769c9bd32c" PRIMARY KEY ("id", "inCommonId")`);
        await queryRunner.query(`ALTER TABLE "artist" ADD "inCommonCreatedat" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "artist" ADD "inCommonUpdatedat" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "label" DROP CONSTRAINT "PK_c13d439ff044a8eb362be1b8249"`);
        await queryRunner.query(`ALTER TABLE "label" DROP COLUMN "inCommonId"`);
        await queryRunner.query(`ALTER TABLE "label" ADD "inCommonId" SERIAL NOT NULL`);
        await queryRunner.query(`ALTER TABLE "label" ADD CONSTRAINT "PK_c13d439ff044a8eb362be1b8249" PRIMARY KEY ("inCommonId")`);
        await queryRunner.query(`ALTER TABLE "music" DROP CONSTRAINT "PK_f25670f217aeb2cac08bfbf2121"`);
        await queryRunner.query(`ALTER TABLE "music" DROP COLUMN "inCommonId"`);
        await queryRunner.query(`ALTER TABLE "music" ADD "inCommonId" SERIAL NOT NULL`);
        await queryRunner.query(`ALTER TABLE "music" ADD CONSTRAINT "PK_f25670f217aeb2cac08bfbf2121" PRIMARY KEY ("inCommonId")`);
        await queryRunner.query(`ALTER TABLE "record" DROP CONSTRAINT "PK_8971bb60434b1f1e8aa36f21cd5"`);
        await queryRunner.query(`ALTER TABLE "record" DROP COLUMN "inCommonId"`);
        await queryRunner.query(`ALTER TABLE "record" ADD "inCommonId" SERIAL NOT NULL`);
        await queryRunner.query(`ALTER TABLE "record" ADD CONSTRAINT "PK_8971bb60434b1f1e8aa36f21cd5" PRIMARY KEY ("inCommonId")`);
        await queryRunner.query(`ALTER TABLE "band" DROP CONSTRAINT "PK_e6d868dc2eb3fa0299d4fbd0e8d"`);
        await queryRunner.query(`ALTER TABLE "band" DROP COLUMN "inCommonId"`);
        await queryRunner.query(`ALTER TABLE "band" ADD "inCommonId" SERIAL NOT NULL`);
        await queryRunner.query(`ALTER TABLE "band" ADD CONSTRAINT "PK_e6d868dc2eb3fa0299d4fbd0e8d" PRIMARY KEY ("inCommonId")`);
        await queryRunner.query(`ALTER TABLE "user" DROP CONSTRAINT "PK_a902b69d72e9e1881e86ce51c73"`);
        await queryRunner.query(`ALTER TABLE "user" DROP COLUMN "inCommonId"`);
        await queryRunner.query(`ALTER TABLE "user" ADD "inCommonId" SERIAL NOT NULL`);
        await queryRunner.query(`ALTER TABLE "user" ADD CONSTRAINT "PK_a902b69d72e9e1881e86ce51c73" PRIMARY KEY ("inCommonId")`);
        await queryRunner.query(`ALTER TABLE "label_users_user" ADD CONSTRAINT "FK_088f637a172dab5f8a9508646d0" FOREIGN KEY ("labelInCommonId") REFERENCES "label"("inCommonId") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "label_users_user" ADD CONSTRAINT "FK_94a293541ce58e345277821f67b" FOREIGN KEY ("userInCommonId") REFERENCES "user"("inCommonId") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "label_records_record" ADD CONSTRAINT "FK_b4d2c533e79535b79ecf15e5d6a" FOREIGN KEY ("labelInCommonId") REFERENCES "label"("inCommonId") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "label_records_record" ADD CONSTRAINT "FK_1b853c485545482e80adef1cd04" FOREIGN KEY ("recordInCommonId") REFERENCES "record"("inCommonId") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "label_musics_music" ADD CONSTRAINT "FK_b3d4ecb49b1652d20316f0463cd" FOREIGN KEY ("labelInCommonId") REFERENCES "label"("inCommonId") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "label_musics_music" ADD CONSTRAINT "FK_4e029615a53cea0d2a4c43c868a" FOREIGN KEY ("musicInCommonId") REFERENCES "music"("inCommonId") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "label_bands_band" ADD CONSTRAINT "FK_da5243cecb29840e6aaa043bf91" FOREIGN KEY ("labelInCommonId") REFERENCES "label"("inCommonId") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "label_bands_band" ADD CONSTRAINT "FK_5a0a392c6e3c47242e0663cd0f2" FOREIGN KEY ("bandInCommonId") REFERENCES "band"("inCommonId") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "label_artists_artist" ADD CONSTRAINT "FK_f305bb394076e0908217d1ca5ad" FOREIGN KEY ("labelInCommonId") REFERENCES "label"("inCommonId") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "label_artists_artist" ADD CONSTRAINT "FK_65992b1a5580f3ff4e4a5669401" FOREIGN KEY ("artistInCommonId") REFERENCES "artist"("inCommonId") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "music_users_user" ADD CONSTRAINT "FK_00b4e628cc01e82fe007f6f763e" FOREIGN KEY ("musicInCommonId") REFERENCES "music"("inCommonId") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "music_users_user" ADD CONSTRAINT "FK_57ed247d1ff420dc8c13645bbc0" FOREIGN KEY ("userInCommonId") REFERENCES "user"("inCommonId") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "music_records_record" ADD CONSTRAINT "FK_4a7735e89ad4f3b65b2510cef68" FOREIGN KEY ("musicInCommonId") REFERENCES "music"("inCommonId") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "music_records_record" ADD CONSTRAINT "FK_6a92b165ab4cb0b912eeefc870d" FOREIGN KEY ("recordInCommonId") REFERENCES "record"("inCommonId") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "music_labels_label" ADD CONSTRAINT "FK_c4f803b5c7b3afe82483d6874c4" FOREIGN KEY ("musicInCommonId") REFERENCES "music"("inCommonId") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "music_labels_label" ADD CONSTRAINT "FK_942627b8813020cc805cb366179" FOREIGN KEY ("labelInCommonId") REFERENCES "label"("inCommonId") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "music_bands_band" ADD CONSTRAINT "FK_3ed21a53a1796c72c657f10252a" FOREIGN KEY ("musicInCommonId") REFERENCES "music"("inCommonId") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "music_bands_band" ADD CONSTRAINT "FK_7cca8c88113973af66867c1680b" FOREIGN KEY ("bandInCommonId") REFERENCES "band"("inCommonId") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "music_artists_artist" ADD CONSTRAINT "FK_8a282f602f8c5b8cd1426f72b18" FOREIGN KEY ("musicInCommonId") REFERENCES "music"("inCommonId") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "music_artists_artist" ADD CONSTRAINT "FK_1deee4cef6329447199d1a82b04" FOREIGN KEY ("artistInCommonId") REFERENCES "artist"("inCommonId") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "record_users_user" ADD CONSTRAINT "FK_8c54e6e11d4b720d3df02717749" FOREIGN KEY ("recordInCommonId") REFERENCES "record"("inCommonId") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "record_users_user" ADD CONSTRAINT "FK_532851282aa95c4b401d3d9b577" FOREIGN KEY ("userInCommonId") REFERENCES "user"("inCommonId") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "record_artists_artist" ADD CONSTRAINT "FK_122ec5f408072ac39b5828351e7" FOREIGN KEY ("recordInCommonId") REFERENCES "record"("inCommonId") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "record_artists_artist" ADD CONSTRAINT "FK_72497cff25641b2c6fd707cd5bc" FOREIGN KEY ("artistInCommonId") REFERENCES "artist"("inCommonId") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "record_musics_music" ADD CONSTRAINT "FK_9d3793a9465edcdc4135e9e9200" FOREIGN KEY ("recordInCommonId") REFERENCES "record"("inCommonId") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "record_musics_music" ADD CONSTRAINT "FK_d9ebcd967ce415f2333dcf61bec" FOREIGN KEY ("musicInCommonId") REFERENCES "music"("inCommonId") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "record_labels_label" ADD CONSTRAINT "FK_6da6ad4991a07cdf1c92ae448de" FOREIGN KEY ("recordInCommonId") REFERENCES "record"("inCommonId") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "record_labels_label" ADD CONSTRAINT "FK_fe339ee5850d83bc3c3954b9474" FOREIGN KEY ("labelInCommonId") REFERENCES "label"("inCommonId") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "record_bands_band" ADD CONSTRAINT "FK_0cc0e20eae5bc8ca2a87853806d" FOREIGN KEY ("recordInCommonId") REFERENCES "record"("inCommonId") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "record_bands_band" ADD CONSTRAINT "FK_b3924c38c2c4a34483d5ad034df" FOREIGN KEY ("bandInCommonId") REFERENCES "band"("inCommonId") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "band_users_user" ADD CONSTRAINT "FK_74662db770bb8884b284a43a6af" FOREIGN KEY ("bandInCommonId") REFERENCES "band"("inCommonId") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "band_users_user" ADD CONSTRAINT "FK_b0f9235ad70191593bd96ebb90b" FOREIGN KEY ("userInCommonId") REFERENCES "user"("inCommonId") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "band_records_record" ADD CONSTRAINT "FK_b584fd834262789d0f3086d2f6e" FOREIGN KEY ("bandInCommonId") REFERENCES "band"("inCommonId") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "band_records_record" ADD CONSTRAINT "FK_38096136ba3b4119bb31ad2c445" FOREIGN KEY ("recordInCommonId") REFERENCES "record"("inCommonId") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "band_musics_music" ADD CONSTRAINT "FK_067e03d51d85b0e2f6473dc5c43" FOREIGN KEY ("bandInCommonId") REFERENCES "band"("inCommonId") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "band_musics_music" ADD CONSTRAINT "FK_24e73c43d1a4d89bc1f5a0662e6" FOREIGN KEY ("musicInCommonId") REFERENCES "music"("inCommonId") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "band_bands_label" ADD CONSTRAINT "FK_6affa0410a03ad9a8a68aff0242" FOREIGN KEY ("bandInCommonId") REFERENCES "band"("inCommonId") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "band_bands_label" ADD CONSTRAINT "FK_96b32d5c5c943b8af4544182654" FOREIGN KEY ("labelInCommonId") REFERENCES "label"("inCommonId") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "band_artists_artist" ADD CONSTRAINT "FK_e7855b11ccff98db09958164252" FOREIGN KEY ("bandInCommonId") REFERENCES "band"("inCommonId") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "band_artists_artist" ADD CONSTRAINT "FK_6c8f852fff64cf4078a812fc0f0" FOREIGN KEY ("artistInCommonId") REFERENCES "artist"("inCommonId") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_artists_artist" ADD CONSTRAINT "FK_864f718bb7d05a873f70ff39403" FOREIGN KEY ("userInCommonId") REFERENCES "user"("inCommonId") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_artists_artist" ADD CONSTRAINT "FK_3e2b4550bdfc4dd7f57bfd6104b" FOREIGN KEY ("artistInCommonId") REFERENCES "artist"("inCommonId") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_bands_band" ADD CONSTRAINT "FK_9a058a99805c83eb6d67620dfd9" FOREIGN KEY ("userInCommonId") REFERENCES "user"("inCommonId") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_bands_band" ADD CONSTRAINT "FK_fa54807f630585e4de1ee8f7eba" FOREIGN KEY ("bandInCommonId") REFERENCES "band"("inCommonId") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_musics_music" ADD CONSTRAINT "FK_e130dc5275cbd1600ac57e515c1" FOREIGN KEY ("userInCommonId") REFERENCES "user"("inCommonId") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_musics_music" ADD CONSTRAINT "FK_acd8384b766cc1c0672d7a99765" FOREIGN KEY ("musicInCommonId") REFERENCES "music"("inCommonId") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_records_record" ADD CONSTRAINT "FK_dd2b6eee7e6ceea7833acb2ce3f" FOREIGN KEY ("userInCommonId") REFERENCES "user"("inCommonId") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_records_record" ADD CONSTRAINT "FK_84d0c447b1d35e74d39aa9e7a7e" FOREIGN KEY ("recordInCommonId") REFERENCES "record"("inCommonId") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_labels_label" ADD CONSTRAINT "FK_89b59b0e5441a78e66f82e4ddef" FOREIGN KEY ("userInCommonId") REFERENCES "user"("inCommonId") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_labels_label" ADD CONSTRAINT "FK_d1ea408c2c23987b11dc7ff0a24" FOREIGN KEY ("labelInCommonId") REFERENCES "label"("inCommonId") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "artist_users_user" ADD CONSTRAINT "FK_f95f99d3ebce89d8cdd8bcd4312" FOREIGN KEY ("artistInCommonId") REFERENCES "artist"("inCommonId") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "artist_users_user" ADD CONSTRAINT "FK_4215f397941e0efe5ac7f6fcad8" FOREIGN KEY ("userInCommonId") REFERENCES "user"("inCommonId") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "artist_records_record" ADD CONSTRAINT "FK_90fdf85120e88a46acf16f29967" FOREIGN KEY ("artistInCommonId") REFERENCES "artist"("inCommonId") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "artist_records_record" ADD CONSTRAINT "FK_6f417ea9c08b6657f620225fee1" FOREIGN KEY ("recordInCommonId") REFERENCES "record"("inCommonId") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "artist_musics_music" ADD CONSTRAINT "FK_6fb690fb895d691ab918734f61d" FOREIGN KEY ("artistInCommonId") REFERENCES "artist"("inCommonId") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "artist_musics_music" ADD CONSTRAINT "FK_aaf98810dcea4847b5373c3c7d1" FOREIGN KEY ("musicInCommonId") REFERENCES "music"("inCommonId") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "artist_labels_label" ADD CONSTRAINT "FK_991f42e0b968c18bf9029c2c055" FOREIGN KEY ("artistInCommonId") REFERENCES "artist"("inCommonId") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "artist_labels_label" ADD CONSTRAINT "FK_7cb57bba282f5a53395d2f0c6c8" FOREIGN KEY ("labelInCommonId") REFERENCES "label"("inCommonId") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "artist_bands_band" ADD CONSTRAINT "FK_8f1a6760399cece036e086bd795" FOREIGN KEY ("artistInCommonId") REFERENCES "artist"("inCommonId") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "artist_bands_band" ADD CONSTRAINT "FK_74d67fa805e303e2508c420a397" FOREIGN KEY ("bandInCommonId") REFERENCES "band"("inCommonId") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "artist_bands_band" DROP CONSTRAINT "FK_74d67fa805e303e2508c420a397"`);
        await queryRunner.query(`ALTER TABLE "artist_bands_band" DROP CONSTRAINT "FK_8f1a6760399cece036e086bd795"`);
        await queryRunner.query(`ALTER TABLE "artist_labels_label" DROP CONSTRAINT "FK_7cb57bba282f5a53395d2f0c6c8"`);
        await queryRunner.query(`ALTER TABLE "artist_labels_label" DROP CONSTRAINT "FK_991f42e0b968c18bf9029c2c055"`);
        await queryRunner.query(`ALTER TABLE "artist_musics_music" DROP CONSTRAINT "FK_aaf98810dcea4847b5373c3c7d1"`);
        await queryRunner.query(`ALTER TABLE "artist_musics_music" DROP CONSTRAINT "FK_6fb690fb895d691ab918734f61d"`);
        await queryRunner.query(`ALTER TABLE "artist_records_record" DROP CONSTRAINT "FK_6f417ea9c08b6657f620225fee1"`);
        await queryRunner.query(`ALTER TABLE "artist_records_record" DROP CONSTRAINT "FK_90fdf85120e88a46acf16f29967"`);
        await queryRunner.query(`ALTER TABLE "artist_users_user" DROP CONSTRAINT "FK_4215f397941e0efe5ac7f6fcad8"`);
        await queryRunner.query(`ALTER TABLE "artist_users_user" DROP CONSTRAINT "FK_f95f99d3ebce89d8cdd8bcd4312"`);
        await queryRunner.query(`ALTER TABLE "user_labels_label" DROP CONSTRAINT "FK_d1ea408c2c23987b11dc7ff0a24"`);
        await queryRunner.query(`ALTER TABLE "user_labels_label" DROP CONSTRAINT "FK_89b59b0e5441a78e66f82e4ddef"`);
        await queryRunner.query(`ALTER TABLE "user_records_record" DROP CONSTRAINT "FK_84d0c447b1d35e74d39aa9e7a7e"`);
        await queryRunner.query(`ALTER TABLE "user_records_record" DROP CONSTRAINT "FK_dd2b6eee7e6ceea7833acb2ce3f"`);
        await queryRunner.query(`ALTER TABLE "user_musics_music" DROP CONSTRAINT "FK_acd8384b766cc1c0672d7a99765"`);
        await queryRunner.query(`ALTER TABLE "user_musics_music" DROP CONSTRAINT "FK_e130dc5275cbd1600ac57e515c1"`);
        await queryRunner.query(`ALTER TABLE "user_bands_band" DROP CONSTRAINT "FK_fa54807f630585e4de1ee8f7eba"`);
        await queryRunner.query(`ALTER TABLE "user_bands_band" DROP CONSTRAINT "FK_9a058a99805c83eb6d67620dfd9"`);
        await queryRunner.query(`ALTER TABLE "user_artists_artist" DROP CONSTRAINT "FK_3e2b4550bdfc4dd7f57bfd6104b"`);
        await queryRunner.query(`ALTER TABLE "user_artists_artist" DROP CONSTRAINT "FK_864f718bb7d05a873f70ff39403"`);
        await queryRunner.query(`ALTER TABLE "band_artists_artist" DROP CONSTRAINT "FK_6c8f852fff64cf4078a812fc0f0"`);
        await queryRunner.query(`ALTER TABLE "band_artists_artist" DROP CONSTRAINT "FK_e7855b11ccff98db09958164252"`);
        await queryRunner.query(`ALTER TABLE "band_bands_label" DROP CONSTRAINT "FK_96b32d5c5c943b8af4544182654"`);
        await queryRunner.query(`ALTER TABLE "band_bands_label" DROP CONSTRAINT "FK_6affa0410a03ad9a8a68aff0242"`);
        await queryRunner.query(`ALTER TABLE "band_musics_music" DROP CONSTRAINT "FK_24e73c43d1a4d89bc1f5a0662e6"`);
        await queryRunner.query(`ALTER TABLE "band_musics_music" DROP CONSTRAINT "FK_067e03d51d85b0e2f6473dc5c43"`);
        await queryRunner.query(`ALTER TABLE "band_records_record" DROP CONSTRAINT "FK_38096136ba3b4119bb31ad2c445"`);
        await queryRunner.query(`ALTER TABLE "band_records_record" DROP CONSTRAINT "FK_b584fd834262789d0f3086d2f6e"`);
        await queryRunner.query(`ALTER TABLE "band_users_user" DROP CONSTRAINT "FK_b0f9235ad70191593bd96ebb90b"`);
        await queryRunner.query(`ALTER TABLE "band_users_user" DROP CONSTRAINT "FK_74662db770bb8884b284a43a6af"`);
        await queryRunner.query(`ALTER TABLE "record_bands_band" DROP CONSTRAINT "FK_b3924c38c2c4a34483d5ad034df"`);
        await queryRunner.query(`ALTER TABLE "record_bands_band" DROP CONSTRAINT "FK_0cc0e20eae5bc8ca2a87853806d"`);
        await queryRunner.query(`ALTER TABLE "record_labels_label" DROP CONSTRAINT "FK_fe339ee5850d83bc3c3954b9474"`);
        await queryRunner.query(`ALTER TABLE "record_labels_label" DROP CONSTRAINT "FK_6da6ad4991a07cdf1c92ae448de"`);
        await queryRunner.query(`ALTER TABLE "record_musics_music" DROP CONSTRAINT "FK_d9ebcd967ce415f2333dcf61bec"`);
        await queryRunner.query(`ALTER TABLE "record_musics_music" DROP CONSTRAINT "FK_9d3793a9465edcdc4135e9e9200"`);
        await queryRunner.query(`ALTER TABLE "record_artists_artist" DROP CONSTRAINT "FK_72497cff25641b2c6fd707cd5bc"`);
        await queryRunner.query(`ALTER TABLE "record_artists_artist" DROP CONSTRAINT "FK_122ec5f408072ac39b5828351e7"`);
        await queryRunner.query(`ALTER TABLE "record_users_user" DROP CONSTRAINT "FK_532851282aa95c4b401d3d9b577"`);
        await queryRunner.query(`ALTER TABLE "record_users_user" DROP CONSTRAINT "FK_8c54e6e11d4b720d3df02717749"`);
        await queryRunner.query(`ALTER TABLE "music_artists_artist" DROP CONSTRAINT "FK_1deee4cef6329447199d1a82b04"`);
        await queryRunner.query(`ALTER TABLE "music_artists_artist" DROP CONSTRAINT "FK_8a282f602f8c5b8cd1426f72b18"`);
        await queryRunner.query(`ALTER TABLE "music_bands_band" DROP CONSTRAINT "FK_7cca8c88113973af66867c1680b"`);
        await queryRunner.query(`ALTER TABLE "music_bands_band" DROP CONSTRAINT "FK_3ed21a53a1796c72c657f10252a"`);
        await queryRunner.query(`ALTER TABLE "music_labels_label" DROP CONSTRAINT "FK_942627b8813020cc805cb366179"`);
        await queryRunner.query(`ALTER TABLE "music_labels_label" DROP CONSTRAINT "FK_c4f803b5c7b3afe82483d6874c4"`);
        await queryRunner.query(`ALTER TABLE "music_records_record" DROP CONSTRAINT "FK_6a92b165ab4cb0b912eeefc870d"`);
        await queryRunner.query(`ALTER TABLE "music_records_record" DROP CONSTRAINT "FK_4a7735e89ad4f3b65b2510cef68"`);
        await queryRunner.query(`ALTER TABLE "music_users_user" DROP CONSTRAINT "FK_57ed247d1ff420dc8c13645bbc0"`);
        await queryRunner.query(`ALTER TABLE "music_users_user" DROP CONSTRAINT "FK_00b4e628cc01e82fe007f6f763e"`);
        await queryRunner.query(`ALTER TABLE "label_artists_artist" DROP CONSTRAINT "FK_65992b1a5580f3ff4e4a5669401"`);
        await queryRunner.query(`ALTER TABLE "label_artists_artist" DROP CONSTRAINT "FK_f305bb394076e0908217d1ca5ad"`);
        await queryRunner.query(`ALTER TABLE "label_bands_band" DROP CONSTRAINT "FK_5a0a392c6e3c47242e0663cd0f2"`);
        await queryRunner.query(`ALTER TABLE "label_bands_band" DROP CONSTRAINT "FK_da5243cecb29840e6aaa043bf91"`);
        await queryRunner.query(`ALTER TABLE "label_musics_music" DROP CONSTRAINT "FK_4e029615a53cea0d2a4c43c868a"`);
        await queryRunner.query(`ALTER TABLE "label_musics_music" DROP CONSTRAINT "FK_b3d4ecb49b1652d20316f0463cd"`);
        await queryRunner.query(`ALTER TABLE "label_records_record" DROP CONSTRAINT "FK_1b853c485545482e80adef1cd04"`);
        await queryRunner.query(`ALTER TABLE "label_records_record" DROP CONSTRAINT "FK_b4d2c533e79535b79ecf15e5d6a"`);
        await queryRunner.query(`ALTER TABLE "label_users_user" DROP CONSTRAINT "FK_94a293541ce58e345277821f67b"`);
        await queryRunner.query(`ALTER TABLE "label_users_user" DROP CONSTRAINT "FK_088f637a172dab5f8a9508646d0"`);
        await queryRunner.query(`ALTER TABLE "user" DROP CONSTRAINT "PK_a902b69d72e9e1881e86ce51c73"`);
        await queryRunner.query(`ALTER TABLE "user" DROP COLUMN "inCommonId"`);
        await queryRunner.query(`ALTER TABLE "user" ADD "inCommonId" uuid NOT NULL DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "user" ADD CONSTRAINT "PK_a902b69d72e9e1881e86ce51c73" PRIMARY KEY ("inCommonId")`);
        await queryRunner.query(`ALTER TABLE "band" DROP CONSTRAINT "PK_e6d868dc2eb3fa0299d4fbd0e8d"`);
        await queryRunner.query(`ALTER TABLE "band" DROP COLUMN "inCommonId"`);
        await queryRunner.query(`ALTER TABLE "band" ADD "inCommonId" uuid NOT NULL DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "band" ADD CONSTRAINT "PK_e6d868dc2eb3fa0299d4fbd0e8d" PRIMARY KEY ("inCommonId")`);
        await queryRunner.query(`ALTER TABLE "record" DROP CONSTRAINT "PK_8971bb60434b1f1e8aa36f21cd5"`);
        await queryRunner.query(`ALTER TABLE "record" DROP COLUMN "inCommonId"`);
        await queryRunner.query(`ALTER TABLE "record" ADD "inCommonId" uuid NOT NULL DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "record" ADD CONSTRAINT "PK_8971bb60434b1f1e8aa36f21cd5" PRIMARY KEY ("inCommonId")`);
        await queryRunner.query(`ALTER TABLE "music" DROP CONSTRAINT "PK_f25670f217aeb2cac08bfbf2121"`);
        await queryRunner.query(`ALTER TABLE "music" DROP COLUMN "inCommonId"`);
        await queryRunner.query(`ALTER TABLE "music" ADD "inCommonId" uuid NOT NULL DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "music" ADD CONSTRAINT "PK_f25670f217aeb2cac08bfbf2121" PRIMARY KEY ("inCommonId")`);
        await queryRunner.query(`ALTER TABLE "label" DROP CONSTRAINT "PK_c13d439ff044a8eb362be1b8249"`);
        await queryRunner.query(`ALTER TABLE "label" DROP COLUMN "inCommonId"`);
        await queryRunner.query(`ALTER TABLE "label" ADD "inCommonId" uuid NOT NULL DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "label" ADD CONSTRAINT "PK_c13d439ff044a8eb362be1b8249" PRIMARY KEY ("inCommonId")`);
        await queryRunner.query(`ALTER TABLE "artist" DROP COLUMN "inCommonUpdatedat"`);
        await queryRunner.query(`ALTER TABLE "artist" DROP COLUMN "inCommonCreatedat"`);
        await queryRunner.query(`ALTER TABLE "artist" DROP CONSTRAINT "PK_10c1796675df147b3769c9bd32c"`);
        await queryRunner.query(`ALTER TABLE "artist" ADD CONSTRAINT "PK_55b76e71568b5db4d01d3e394ed" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "artist" DROP COLUMN "inCommonId"`);
        await queryRunner.query(`ALTER TABLE "artist" DROP COLUMN "followers"`);
        await queryRunner.query(`ALTER TABLE "artist" DROP COLUMN "likes"`);
        await queryRunner.query(`ALTER TABLE "artist" DROP COLUMN "passing"`);
        await queryRunner.query(`ALTER TABLE "artist" DROP COLUMN "birthday"`);
        await queryRunner.query(`ALTER TABLE "artist" DROP COLUMN "name"`);
        await queryRunner.query(`ALTER TABLE "artist" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "artist" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "artist" DROP CONSTRAINT "PK_55b76e71568b5db4d01d3e394ed"`);
        await queryRunner.query(`ALTER TABLE "artist" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "artist" ADD "id" uuid NOT NULL DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "artist" ADD CONSTRAINT "PK_55b76e71568b5db4d01d3e394ed" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "artist" ADD "createdAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "artist" ADD "updatedAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "artist" ADD "name" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "artist" ADD "birthday" TIMESTAMP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "artist" ADD "passing" TIMESTAMP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "artist" ADD "likes" integer NOT NULL`);
        await queryRunner.query(`ALTER TABLE "artist" ADD "followers" integer NOT NULL`);
        await queryRunner.query(`ALTER TABLE "artist" ADD "inCommonId" uuid NOT NULL DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "artist" DROP CONSTRAINT "PK_55b76e71568b5db4d01d3e394ed"`);
        await queryRunner.query(`ALTER TABLE "artist" ADD CONSTRAINT "PK_10c1796675df147b3769c9bd32c" PRIMARY KEY ("id", "inCommonId")`);
        await queryRunner.query(`ALTER TABLE "artist" ADD "inCommonCreatedat" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "artist" ADD "inCommonUpdatedat" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`DROP INDEX "IDX_74d67fa805e303e2508c420a39"`);
        await queryRunner.query(`DROP INDEX "IDX_8f1a6760399cece036e086bd79"`);
        await queryRunner.query(`DROP TABLE "artist_bands_band"`);
        await queryRunner.query(`DROP INDEX "IDX_7cb57bba282f5a53395d2f0c6c"`);
        await queryRunner.query(`DROP INDEX "IDX_991f42e0b968c18bf9029c2c05"`);
        await queryRunner.query(`DROP TABLE "artist_labels_label"`);
        await queryRunner.query(`DROP INDEX "IDX_aaf98810dcea4847b5373c3c7d"`);
        await queryRunner.query(`DROP INDEX "IDX_6fb690fb895d691ab918734f61"`);
        await queryRunner.query(`DROP TABLE "artist_musics_music"`);
        await queryRunner.query(`DROP INDEX "IDX_6f417ea9c08b6657f620225fee"`);
        await queryRunner.query(`DROP INDEX "IDX_90fdf85120e88a46acf16f2996"`);
        await queryRunner.query(`DROP TABLE "artist_records_record"`);
        await queryRunner.query(`DROP INDEX "IDX_4215f397941e0efe5ac7f6fcad"`);
        await queryRunner.query(`DROP INDEX "IDX_f95f99d3ebce89d8cdd8bcd431"`);
        await queryRunner.query(`DROP TABLE "artist_users_user"`);
        await queryRunner.query(`DROP INDEX "IDX_d1ea408c2c23987b11dc7ff0a2"`);
        await queryRunner.query(`DROP INDEX "IDX_89b59b0e5441a78e66f82e4dde"`);
        await queryRunner.query(`DROP TABLE "user_labels_label"`);
        await queryRunner.query(`DROP INDEX "IDX_84d0c447b1d35e74d39aa9e7a7"`);
        await queryRunner.query(`DROP INDEX "IDX_dd2b6eee7e6ceea7833acb2ce3"`);
        await queryRunner.query(`DROP TABLE "user_records_record"`);
        await queryRunner.query(`DROP INDEX "IDX_acd8384b766cc1c0672d7a9976"`);
        await queryRunner.query(`DROP INDEX "IDX_e130dc5275cbd1600ac57e515c"`);
        await queryRunner.query(`DROP TABLE "user_musics_music"`);
        await queryRunner.query(`DROP INDEX "IDX_fa54807f630585e4de1ee8f7eb"`);
        await queryRunner.query(`DROP INDEX "IDX_9a058a99805c83eb6d67620dfd"`);
        await queryRunner.query(`DROP TABLE "user_bands_band"`);
        await queryRunner.query(`DROP INDEX "IDX_3e2b4550bdfc4dd7f57bfd6104"`);
        await queryRunner.query(`DROP INDEX "IDX_864f718bb7d05a873f70ff3940"`);
        await queryRunner.query(`DROP TABLE "user_artists_artist"`);
        await queryRunner.query(`DROP INDEX "IDX_6c8f852fff64cf4078a812fc0f"`);
        await queryRunner.query(`DROP INDEX "IDX_e7855b11ccff98db0995816425"`);
        await queryRunner.query(`DROP TABLE "band_artists_artist"`);
        await queryRunner.query(`DROP INDEX "IDX_96b32d5c5c943b8af454418265"`);
        await queryRunner.query(`DROP INDEX "IDX_6affa0410a03ad9a8a68aff024"`);
        await queryRunner.query(`DROP TABLE "band_bands_label"`);
        await queryRunner.query(`DROP INDEX "IDX_24e73c43d1a4d89bc1f5a0662e"`);
        await queryRunner.query(`DROP INDEX "IDX_067e03d51d85b0e2f6473dc5c4"`);
        await queryRunner.query(`DROP TABLE "band_musics_music"`);
        await queryRunner.query(`DROP INDEX "IDX_38096136ba3b4119bb31ad2c44"`);
        await queryRunner.query(`DROP INDEX "IDX_b584fd834262789d0f3086d2f6"`);
        await queryRunner.query(`DROP TABLE "band_records_record"`);
        await queryRunner.query(`DROP INDEX "IDX_b0f9235ad70191593bd96ebb90"`);
        await queryRunner.query(`DROP INDEX "IDX_74662db770bb8884b284a43a6a"`);
        await queryRunner.query(`DROP TABLE "band_users_user"`);
        await queryRunner.query(`DROP INDEX "IDX_b3924c38c2c4a34483d5ad034d"`);
        await queryRunner.query(`DROP INDEX "IDX_0cc0e20eae5bc8ca2a87853806"`);
        await queryRunner.query(`DROP TABLE "record_bands_band"`);
        await queryRunner.query(`DROP INDEX "IDX_fe339ee5850d83bc3c3954b947"`);
        await queryRunner.query(`DROP INDEX "IDX_6da6ad4991a07cdf1c92ae448d"`);
        await queryRunner.query(`DROP TABLE "record_labels_label"`);
        await queryRunner.query(`DROP INDEX "IDX_d9ebcd967ce415f2333dcf61be"`);
        await queryRunner.query(`DROP INDEX "IDX_9d3793a9465edcdc4135e9e920"`);
        await queryRunner.query(`DROP TABLE "record_musics_music"`);
        await queryRunner.query(`DROP INDEX "IDX_72497cff25641b2c6fd707cd5b"`);
        await queryRunner.query(`DROP INDEX "IDX_122ec5f408072ac39b5828351e"`);
        await queryRunner.query(`DROP TABLE "record_artists_artist"`);
        await queryRunner.query(`DROP INDEX "IDX_532851282aa95c4b401d3d9b57"`);
        await queryRunner.query(`DROP INDEX "IDX_8c54e6e11d4b720d3df0271774"`);
        await queryRunner.query(`DROP TABLE "record_users_user"`);
        await queryRunner.query(`DROP INDEX "IDX_1deee4cef6329447199d1a82b0"`);
        await queryRunner.query(`DROP INDEX "IDX_8a282f602f8c5b8cd1426f72b1"`);
        await queryRunner.query(`DROP TABLE "music_artists_artist"`);
        await queryRunner.query(`DROP INDEX "IDX_7cca8c88113973af66867c1680"`);
        await queryRunner.query(`DROP INDEX "IDX_3ed21a53a1796c72c657f10252"`);
        await queryRunner.query(`DROP TABLE "music_bands_band"`);
        await queryRunner.query(`DROP INDEX "IDX_942627b8813020cc805cb36617"`);
        await queryRunner.query(`DROP INDEX "IDX_c4f803b5c7b3afe82483d6874c"`);
        await queryRunner.query(`DROP TABLE "music_labels_label"`);
        await queryRunner.query(`DROP INDEX "IDX_6a92b165ab4cb0b912eeefc870"`);
        await queryRunner.query(`DROP INDEX "IDX_4a7735e89ad4f3b65b2510cef6"`);
        await queryRunner.query(`DROP TABLE "music_records_record"`);
        await queryRunner.query(`DROP INDEX "IDX_57ed247d1ff420dc8c13645bbc"`);
        await queryRunner.query(`DROP INDEX "IDX_00b4e628cc01e82fe007f6f763"`);
        await queryRunner.query(`DROP TABLE "music_users_user"`);
        await queryRunner.query(`DROP INDEX "IDX_65992b1a5580f3ff4e4a566940"`);
        await queryRunner.query(`DROP INDEX "IDX_f305bb394076e0908217d1ca5a"`);
        await queryRunner.query(`DROP TABLE "label_artists_artist"`);
        await queryRunner.query(`DROP INDEX "IDX_5a0a392c6e3c47242e0663cd0f"`);
        await queryRunner.query(`DROP INDEX "IDX_da5243cecb29840e6aaa043bf9"`);
        await queryRunner.query(`DROP TABLE "label_bands_band"`);
        await queryRunner.query(`DROP INDEX "IDX_4e029615a53cea0d2a4c43c868"`);
        await queryRunner.query(`DROP INDEX "IDX_b3d4ecb49b1652d20316f0463c"`);
        await queryRunner.query(`DROP TABLE "label_musics_music"`);
        await queryRunner.query(`DROP INDEX "IDX_1b853c485545482e80adef1cd0"`);
        await queryRunner.query(`DROP INDEX "IDX_b4d2c533e79535b79ecf15e5d6"`);
        await queryRunner.query(`DROP TABLE "label_records_record"`);
        await queryRunner.query(`DROP INDEX "IDX_94a293541ce58e345277821f67"`);
        await queryRunner.query(`DROP INDEX "IDX_088f637a172dab5f8a9508646d"`);
        await queryRunner.query(`DROP TABLE "label_users_user"`);
    }

}
